# Generated by Django 4.2.6 on 2023-10-28 12:39

from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0002_comment_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to=pathlib.PureWindowsPath('C:/Users/O_O/PycharmProjects/fan_server/uploads'))),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletin_board.announcement')),
            ],
        ),
    ]
